### PR TITLE
Overhaul and fixes

### PR DESCRIPTION
**Pull request by berhram**
# Description

App overhaul

## Issues Resolved

1. All the code was rewritten in Kotlin
2. Many memory leaks was fixed
3. App now compile for the latest SDK version, which means that the app will work on all devices
4. Behavior of most code was not touched, this is further work. Only fixes and replaces of some restricted legacy

## Important
I need to check the full functionality of the application, assistance is welcome.

### CODE REVIEW

**Comment by johannesjo** [comment]
Wow! Thank you very much! I will have a look this Friday!

**Comment by johannesjo** [comment]
Unfortunately I won't be able to do this today, but I'll try to have a look on Sunday.

**Comment by johannesjo** [comment]
All seems to be running fine! Thank you!!!!

**Comment by lrq3000** [comment]
Thank you so much for your awesome work @berhram , this greatly simplified further development on the Android app!

**Pull request merged**
