### PR TITLE
Fix stuff

### PR DESCRIPTION
**Pull request by penn5**
# Description

Fix mistakes

## Issues Resolved

Nothing

## Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by penn5** [comment]
The android app is still dramatically, catastrophically broken. This doesn't cover the half of it.

**Comment by johannesjo** [comment]
:D 

Thank you so much!

**Comment by johannesjo** [comment]
Unfortunately I have to revert this, since the app is not usable any more in this state (sync doesn't work and starting a task results in continuous notification sounds).

**Comment by johannesjo** [comment]
Actually it seems like syncing (for dropbox and google drive) was broken by the other PR, so I'll have to revert them both for now I am afraid.

**Comment by penn5** [comment]
> Actually it seems like syncing (for dropbox and google drive) was broken by the other PR, so I'll have to revert them both for now I am afraid.

What issue did you have?

Update: I found the cause of the issue. I'll submit a PR to reapply all the changes including the fix.

**Comment by johannesjo** [comment]
@penn5 that would be great! Thank you very much!

**Pull request merged**
