### PR TITLE
Add API for making HTTP requests

### PR DESCRIPTION
**Pull request by penn5**
New revised edition with fewer bugs

# Description

Same as before

## Issues Resolved

Fixed dropbox, fixed notification sounds when running task. Google drive not tested.

## Check List

- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by johannesjo** [comment]
Thanks for the PR! I'll try to provide feedback as soon as I can!

**Comment by penn5** [comment]
Thanks, just let me know whenever you have time

**Comment by johannesjo** [comment]
Thank you very much for the update! Dropbox and google drive sync now work fine, which is great! I will test this for the next couple of days and hopefully next Thurday I get to merge this. Sorry for the delay. I am pretty busy these days unfortunately :)

**Comment by penn5** [comment]
> Thank you very much for the update! Dropbox and google drive sync now work fine, which is great! I will test this for the next couple of days and hopefully next Thurday I get to merge this. Sorry for the delay. I am pretty busy these days unfortunately :)

Awesome. Thank you!

**Comment by johannesjo** [comment]
Works like a charm! Thank you very much again!

**Pull request merged**
